---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: openvpn
    box: ubuntu/focal64
    interfaces:
      - network_name: private_network
        ip: 192.168.56.203
provisioner:
  name: ansible
verifier:
  name: ansible